name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Cześć! Dzięki za dodanie swojego pierwszego błędu i pomoc w rozwijaniu projektu. ~Skill"
        pr-message: "Cześć! Dzięki za dodanie swojego pierwszego PR! Spróbuję go sprawdzić tak szybko jak to możliwe. ~Skill"
